<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="MAIN" Id="{fef9a243-6a9d-4a61-b10d-d5004d74ff85}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR

VAR_INPUT
	// Elevator inputs
	ElevatorSensor AT %IX1.0: BOOL; // Sensor attached to elevator
	ElevatorTableIsLifted AT %IX1.1: BOOL; // Elevator is currently lifted
	ElevatorTableIsDescended AT %IX1.2: BOOL; // Elevator is currently descended
	
	// Conveyor 2 inputs
	Conveyor2Sensor AT %IX2.0: BOOL; // Sensor attached to second conveyor
	PusherPushed AT %IX2.1: BOOL; // Pusher is pushed
	PusherRetracted AT %IX2.2: BOOL; // Pusher is retracted
END_VAR

VAR_OUTPUT
	// Conveyor 1 outputs
	Conveyor1 AT %QX0.0: BOOL; // First conveyor on/off
	
	// Elevator outputs
	ElevatorConveyor AT %QX1.0: BOOL; // Elevator's conveyor on/off
	ElevatorTableUp AT %QX1.1: BOOL; // Move elevator's table up
	ElevatorTableDown AT %QX1.2: BOOL; // Move elevator's table down
	
	// Conveyor 2 outputs
	Conveyor2 AT %QX2.0: BOOL; // Second conveyor on/off
	PusherPush AT %QX2.1: BOOL; // Push with pusher
	PusherRetract AT %QX2.2: BOOL; // Retract pusher
	
	// Box outputs
	BoxShaker AT %QX3.0: BOOL; // Shake the box
END_VAR]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Fbd"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" />
                  <l2 n="Connectors" />
                  <v n="Id">5L</v>
                </o>
              </l2>
              <v n="BranchCounter">1</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
  </POU>
</TcPlcObject>